version: '3'

services: 
  node:
    container_name: node
    build: 
      context: ark
      dockerfile: node.dockerfile
    ports:
      - "5005:5005"  
    networks:
      - arkapp-network
  mongodb:
    container_name: mongodb
    image: mongo
    networks:
      - arkapp-network

networks:
  arkapp-network:
    driver: bridge
   